### PR TITLE
Fixing config example

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @ntnyq 

I had to adjust the config like this (fixed example) to make it work.

Cheers,
Peter

### CODE REVIEW

**Comment by ntnyq** [comment]
Both [babel-style](https://vuepress.vuejs.org/plugin/using-a-plugin.html#babel-style) and [object-style](https://vuepress.vuejs.org/plugin/using-a-plugin.html#object-style) are supported by VuePress.

Didn't babel-style plugin option work for you?

**Comment by spekulatius** [comment]
That's a good question - I'm not sure. My site is more or less a standard VuePress with a few plugins. Maybe it fails if you used already a different way to configure it?

**Comment by ntnyq** [comment]
Ya. `Babel style` plugin option is wrapped in an array rather than an object which is for object style. 

That means you can use only one plugin option style.

**Comment by spekulatius** [comment]
Ah okay, then this is the issue as it looks. I've followed style I've seen in the docs and plugin installation examples on GitHub - and ran into a conflict here. If we merge this, the issue would be resolved for most people following I think. If not, that's fine too - at least I learn the reasons behind it

**Pull request closed without merging**
